### ISSUE TITLE
Error: Imposible importar nuestro .jar en Django.

### ISSUE THREAD

**Issue by diegarnie** [diegarnie/egc#2]
Autor: Andrés Pachón

Fecha: 17/11/2014 (Primera sesión de integración)

Descripción: El subsistema Cabina de Votación ha intentado utilizar el archivo .jar que les proporcionamos, pero tras estudiarlo han descubierto que no pueden importarlo debido a que su aplicación está siendo desarrollada en Django con Python, y presenta problemas de compatibilidad.

Pasos para reproducir el problema: 
1. Crear un proyecto Django con Eclipse.
2. Tratar de importar nuestro archivo .jar.

Esperado: Importación correcta para poder utilizar nuestros métodos.

Recibido: No es posible importar el archivo.

Versión utilizada: Las versiones de Django, Python o Eclipse son irrelevantes en este caso.

Prioridad: Alta.

Información adicional: Ellos mismos nos proponen una solución, crear una API de nuestra aplicación a la que puedan llamar sin necesidad de importar nuestro código. Se estudiará la viabilidad de dicha propuesta.

**Comment by jmleon** [comment]
Se acepta la propuesta de crear una API para que puedan consultar las claves desde Python. Para crear esta API, se creará un archivo PHP en nuestro Hosting que devuelva la clave pública a partir de una ID de votación. Este archivo se subirá directamente a la rama master del repositorio, pues se considera que el impacto y la incertidumbre del cambio no son suficientes para crear una nueva rama.
