### ISSUE TITLE
Petición cambio de RSA a AES

### ISSUE THREAD

**Issue by diegarnie** [diegarnie/egc#3]
Autor: Andrés Pachón

Fecha: 22/10/2015 

Descripción: El subsistema Cabina de Votación sigue reiterando la necesidad de cambiar de sistema de cifrado. Sugieren utilizar AES en lugar de RSA. Podríamos intentar si no supone mucho cambio.

Prioridad: Baja.

**Comment by jmleon** [comment]
Se acepta el cambio, pero se tratará de añadir la funcionalidad como alternativa sin eliminar lo creado previamente. Para ello se creará una nueva rama que será desechada en caso de que el cambio no pueda realizarse correctamente.
