### ISSUE TITLE
Aumentar el porcentaje de comentarios para mejorar la calidad

### ISSUE THREAD

**Issue by SamuelEGC** [diegarnie/egc#4]
Autor: Samuel Sierra Silva

Fecha: 27/01/2015

Descripción: A través del estudio realizado mediante la herramienta Sonar me he percatado de la ausencia de comentarios en el código. Propongo aumentar el porcentaje de comentarios para mejorar la calidad del código.

Prioridad: Media

Información adicional: Se adjunta la captura de Sonar.
![sin titulo](https://cloud.githubusercontent.com/assets/9352828/5917781/56cfaa36-a621-11e4-8257-5aaefce62bc3.png)

**Comment by jmleon** [comment]
Se acepta el cambio. Se revisará el proyecto y se describirá su funcionamiento con comentarios en el código. Los cambios serán realizados directamente sobre la rama master, ya que el cambio tiene un pequeño impacto y no altera el funcionamiento de la aplicación.
