### ISSUE TITLE
Resolver incidencias detectadas por Sonar

### ISSUE THREAD

**Issue by SamuelEGC** [diegarnie/egc#5]
Autor: Samuel Sierra Silva

Fecha: 27/01/2015

Descripción: Mediante el análisis realizado con Sonar, se han detectado 2 incidencias mayores y 1 incidencia informativa. Propongo que se solucionen ya que considero que no presentan dificultad.

Prioridad: Media

Información adicional: Se adjunta las 2 incidencias mayores y la incidencia informativa en dicho orden.
![borrar](https://cloud.githubusercontent.com/assets/9352828/5918263/0b8849ce-a627-11e4-9c3d-b5f72e9f0509.png)

![borrar2](https://cloud.githubusercontent.com/assets/9352828/5918264/0dce5728-a627-11e4-941f-050e4ed6b48b.png)

**Comment by jmleon** [comment]
Se acepta el cambio. Se realizará la corrección sobre la rama master ya que se trata de cambios menores.

**Comment by jmleon** [comment]
Además de los cambios anteriores, se han realizado otras correcciones para mejorar la calidad que han sido detectadas durante el cambio de las modificaciones propuestas y que no han resultado muy complejas de resolver. En el mensaje de commit se incluye más información sobre dichos cambios.
