### ISSUE TITLE
Error en AuthorityImplAES

### ISSUE THREAD

**Issue by diegarnie** [diegarnie/egc#6]
Autor: Andrés Pachón.
Fecha: 31/01/2015
Descripción: En la clase AuthorityImplAES, si se llama al método getSecretKey() pasando una id de una votación existente se devuelve la clave de cifrado pero incluyendo un espacio en la primera posición. Aunque el cifrado se realiza correctamente, conviene eliminar dicho espacio para evitar algún posible problema futuro.
Pasos para reproducir el problema: 
1. Utilizar el método getSecretKey() de la clase AuthorityImplAES pasando una id existente.

Esperado: La clave de cifrado con un espacio en blanco al principio.
Recibido: La clave sin dicho espacio.
Versión utilizada: La última versión de la aplicación existente en GitHub, con nuestra MV.
Prioridad: Media

**Comment by jmleon** [comment]
Se acepta el cambio. Se realizará el proceso de depuración y se corregirá el bug sobre la rama master.
